/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Color;

/**
 *
 * @author alumno
 */
public class FinestraJList extends javax.swing.JFrame {

    /**
     * Creates new form FinestraJList
     */
    public FinestraJList() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaColors = new javax.swing.JList<>();
        panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        llistaColors = new javax.swing.JList<>();

        listaColors.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Negre", "Blau", "Cyan", "Gris Obscur", "Gris", "Verd",
                "Gris Clar", "Magenta", "Taronja", "Rosa", "Roig", "Blanc", "Groc"};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaColors.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaColorsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaColors);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Llista simple");

        llistaColors.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Negre", "Blau", "Cyan", "Gris Fosc", "Gris", "Verd", "Gris Clar", "Magenta", "Taronja", "Rosa", "Roig", "Blanc", "Groc" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        llistaColors.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                llistaColorsValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(llistaColors);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaColorsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaColorsValueChanged

    }//GEN-LAST:event_listaColorsValueChanged

    private void llistaColorsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_llistaColorsValueChanged
        // TODO add your handling code here:
        switch(llistaColors.getSelectedValue()) {
            case "Negre":
                panel.setBackground(Color.BLACK); break;
            case "Blau":
                panel.setBackground(Color.BLUE); break;
            case "Cyan":
                panel.setBackground(Color.CYAN); break;
            case "Gris Fosc":
                panel.setBackground(Color.DARK_GRAY); break;
            case "Gris":
                panel.setBackground(Color.GRAY); break;
            case "Verd" :
                panel.setBackground(Color.GREEN); break;
            case "Gris Clar" :
                panel.setBackground(Color.LIGHT_GRAY); break;
            case "Magenta":
                panel.setBackground(Color.MAGENTA); break;
            case "Taronja":
                panel.setBackground(Color.ORANGE); break;
            case "Rosa":
                panel.setBackground(Color.PINK); break;
            case "Roig":
                panel.setBackground(Color.RED); break;
            case "Blanc":
                panel.setBackground(Color.WHITE); break;
            case "Groc":
                panel.setBackground(Color.YELLOW); break;
        }
    }//GEN-LAST:event_llistaColorsValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinestraJList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinestraJList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinestraJList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinestraJList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinestraJList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaColors;
    private javax.swing.JList<String> llistaColors;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
