/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.util.Arrays;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.plaf.OptionPaneUI;

/**
 *
 * @author alumno
 */
public class FinestraPrincipal extends javax.swing.JFrame {
    
    char[] ll;
    char[] res;
    String p;
    int cont = 0;
    String lletres = "";
    
    /**
     * Creates new form FinestraPrincipal
     */
    public FinestraPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        lblParaula.setForeground(Color.red);
        tornaAComencar();
    }
    
    public void pasarParaula() {
        for(int i = 0; i < p.length(); i++) {
            ll[i] = p.charAt(i);
        }
    }
    
    public void paraula() {
        String r = "";
        for(int i = 0; i < res.length; i++) {
            r += res[i] + " "; 
        }
        lblParaula.setText(r);
    }
    
    public boolean comprovaGuanyat() {
        boolean a = false;
        for(int i = 0; i < res.length; i++) {
            if(res[i] == '-') {
                a = true;
            }
        }
        return a;
    }
    
    public boolean comprovaLletra(char a) {
        boolean z = false;
        for(int i = 0; i < ll.length; i++) {
            if(ll[i] == a) {
                res[i] = ll[i];
                z = true;
            }
        }
        if(cont != 4) {
            if(!lletraDita(a)) {
                lletres += a + " ";
                lblLletres.setText(lletres);
            } else {
                JOptionPane.showMessageDialog(this, "La lletra ja està dita!!!");
                txtLletra.setText("");
            }   
        } 
        return z;
    }
    
    public boolean comprovarNomesUnaLletra(String z) {
        boolean a = true;
        if(z.length() != 1) {
            JOptionPane.showMessageDialog(this, "Només pots posar una lletra");
            a = false;
        }
        return a;
    }
    
    public void tornaAComencar() {
        lletres = " ";
        lblLletres.setText(" ");
        
        txtParaula.setEnabled(true);
        txtParaula.setText("");
        bAcceptarJ1.setEnabled(true);
        
        txtLletra.setEnabled(false);
        txtLletra.setText("");
        bAcceptarJ2.setEnabled(false);
                
        lblParaula.setText("");
        
        lblImg.setIcon(new ImageIcon("src\\src\\foto1.png"));
        
        cont = 0;
        lblIntents.setText(cont + "");
    }
    
    public boolean lletraDita(char a) {
        boolean z = false;
        for(int j = 0; j < lletres.length(); j++) {
            if(a == lletres.charAt(j)) {
                z = true;
            }
        }
        return z;
    }
    
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblImg = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblLletres = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtParaula = new javax.swing.JTextField();
        bAcceptarJ1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtLletra = new javax.swing.JTextField();
        bAcceptarJ2 = new javax.swing.JButton();
        lblParaula = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblIntents = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Imagen"));

        jLabel3.setText("Letras \"utilizadas\" :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(lblLletres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLletres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Jugador 1"));

        jLabel1.setText("Palabra a adivinar");

        txtParaula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        bAcceptarJ1.setBackground(new java.awt.Color(204, 204, 255));
        bAcceptarJ1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bAcceptarJ1.setText("Aceptar");
        bAcceptarJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAcceptarJ1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bAcceptarJ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtParaula, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 202, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtParaula, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bAcceptarJ1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(245, 245, 245));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Jugador 2"));
        jPanel3.setForeground(new java.awt.Color(204, 255, 255));

        jLabel2.setText("Letra");

        bAcceptarJ2.setText("Aceptar");
        bAcceptarJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAcceptarJ2ActionPerformed(evt);
            }
        });

        lblParaula.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel4.setText("Intentos:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblParaula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAcceptarJ2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(txtLletra)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblIntents, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(lblIntents, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtLletra, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bAcceptarJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblParaula, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAcceptarJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAcceptarJ1ActionPerformed
        // TODO add your handling code here:
        p = txtParaula.getText();
        p = p.toUpperCase();
        
        res = new char[p.length()];
        ll = new char[p.length()];
        String a = "";
        for(int i = 0; i < p.length(); i++) {
            if(p.charAt(i) == ' '){
                a += " ";
                res[i] = ' ';
            } else {
                a += "*";
                res[i] = '-';
            } 
        }
        
        txtParaula.setText(a);
        pasarParaula();
        paraula();
        
        txtParaula.setEnabled(false);
        bAcceptarJ1.setEnabled(false);
        
        txtLletra.setEnabled(true);
        bAcceptarJ2.setEnabled(true);
        
    }//GEN-LAST:event_bAcceptarJ1ActionPerformed

    private void bAcceptarJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAcceptarJ2ActionPerformed
        // TODO add your handling code here:
        String z = txtLletra.getText();
        if(comprovarNomesUnaLletra(z)) {
            z = z.toUpperCase();
            char a = z.charAt(0);
            if(!comprovaLletra(a)) {
                switch(cont) {
                    case 0:
                        lblImg.setIcon(new ImageIcon("src\\src\\foto2.png"));
                        break;
                    case 1:
                        lblImg.setIcon(new ImageIcon("src\\src\\foto3.png"));
                        break;
                    case 2:
                        lblImg.setIcon(new ImageIcon("src\\src\\foto4.png"));
                        break;
                    case 3:
                        lblImg.setIcon(new ImageIcon("src\\src\\foto5.png"));
                        JOptionPane.showMessageDialog(null, "Oh, has perdut");
                        tornaAComencar();
                        break;              
                }
                cont++;
                lblIntents.setText("" + cont);
            } else {
                paraula();
                if(!comprovaGuanyat()) {
                    JOptionPane.showMessageDialog(this, "Molt bé, ho has adivinat!!!");
                    tornaAComencar();
                } 
            }
            txtLletra.setText("");
        } else {
            txtLletra.setText("");
        }
        
    }//GEN-LAST:event_bAcceptarJ2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinestraPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinestraPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinestraPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinestraPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinestraPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAcceptarJ1;
    private javax.swing.JButton bAcceptarJ2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblIntents;
    private javax.swing.JLabel lblLletres;
    private javax.swing.JLabel lblParaula;
    private javax.swing.JTextField txtLletra;
    private javax.swing.JTextField txtParaula;
    // End of variables declaration//GEN-END:variables
}
