/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.*;
import java.util.ArrayList;
import javax.swing.DefaultListModel;


/**
 *
 * @author alumno
 */
public class Finestra_Activitats extends javax.swing.JFrame {
    DefaultListModel<String> model = new DefaultListModel<>();
    
    /**
     * Creates new form Finestra_Activitats
     */
    public Finestra_Activitats() {
        initComponents();
        mostrar();
        llistaExtraescolars.setModel(model);
        setLocationRelativeTo(null);
    }
    
    public void mostrar() {
        ArrayList<String> a = Controlador.extraescolars();
        for(int i = 0; i < a.size(); i++) {
            model.addElement(a.get(i));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bEliminarActivitat = new javax.swing.JButton();
        txtNovaActivitat = new javax.swing.JTextField();
        bAfegirActivitat = new javax.swing.JButton();
        bAcceptar = new javax.swing.JButton();
        lblTitol = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        llistaExtraescolars = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bEliminarActivitat.setText("Eliminar Activitat");
        bEliminarActivitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActivitatActionPerformed(evt);
            }
        });

        bAfegirActivitat.setText("Afegir Activitat");
        bAfegirActivitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAfegirActivitatActionPerformed(evt);
            }
        });

        bAcceptar.setText("Acceptar");
        bAcceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAcceptarActionPerformed(evt);
            }
        });

        lblTitol.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitol.setText("Modificar Activitats Extraescolars");

        jScrollPane1.setViewportView(llistaExtraescolars);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(bEliminarActivitat, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bAfegirActivitat)
                            .addComponent(txtNovaActivitat, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bAcceptar)
                        .addGap(35, 35, 35))))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(lblTitol)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitol)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNovaActivitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bAfegirActivitat))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bEliminarActivitat)
                    .addComponent(bAcceptar))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAcceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAcceptarActionPerformed
        Finestra_Principal a = new Finestra_Principal();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bAcceptarActionPerformed

    private void bAfegirActivitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAfegirActivitatActionPerformed
        String a = txtNovaActivitat.getText();
        if(!a.equals("") || a != null) {
            model.addElement(a);
            Controlador.insertarActivitat(a);
            txtNovaActivitat.setText("");
        }
    }//GEN-LAST:event_bAfegirActivitatActionPerformed

    private void bEliminarActivitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActivitatActionPerformed
        String a = llistaExtraescolars.getSelectedValue();
        Controlador.borrarActivitat(a);
        int index = llistaExtraescolars.getSelectedIndex();
        model.remove(index);
    }//GEN-LAST:event_bEliminarActivitatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finestra_Activitats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finestra_Activitats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finestra_Activitats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finestra_Activitats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Finestra_Activitats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAcceptar;
    private javax.swing.JButton bAfegirActivitat;
    private javax.swing.JButton bEliminarActivitat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitol;
    private javax.swing.JList<String> llistaExtraescolars;
    private javax.swing.JTextField txtNovaActivitat;
    // End of variables declaration//GEN-END:variables
}
