/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.ImageIcon;
import Model.*;
import Controlador.*;

/**
 *
 * @author alumno
 */
public class FinestraPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FinestraPrincipal
     */
    public FinestraPrincipal() {
        initComponents();
        lblImg.setIcon(new ImageIcon("src\\src\\Conill.gif"));
        setLocationRelativeTo(null);
    }
    
    public Client s = new Client();
    public static Controlador c = new Controlador();
    
    public static Controlador getControlador() { return c; }
    public static void setControlador(Controlador a) { c = a; }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitol = new javax.swing.JLabel();
        lblImg = new javax.swing.JLabel();
        bAltaClient = new javax.swing.JButton();
        bGestioEquips = new javax.swing.JButton();
        bEquipsReparacio = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mAltaCl = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mEquips = new javax.swing.JMenuItem();
        mGestio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblTitol.setText("GESTIÓN DE EQUIPOS INFORMÁTICOS");

        bAltaClient.setText("Alta Cliente");
        bAltaClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAltaClientActionPerformed(evt);
            }
        });

        bGestioEquips.setText("Gestión de Equipos");
        bGestioEquips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGestioEquipsActionPerformed(evt);
            }
        });

        bEquipsReparacio.setText("Equipos de Reparación");
        bEquipsReparacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEquipsReparacioActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        mAltaCl.setText("Alta de cliente");
        mAltaCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAltaClActionPerformed(evt);
            }
        });
        jMenu1.add(mAltaCl);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Gestión");

        mEquips.setText("Equipos de reparación");
        mEquips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEquipsActionPerformed(evt);
            }
        });
        jMenu2.add(mEquips);

        mGestio.setText("Gestión de Equipos");
        mGestio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGestioActionPerformed(evt);
            }
        });
        jMenu2.add(mGestio);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(lblTitol, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bGestioEquips, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAltaClient, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bEquipsReparacio))
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitol)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(bAltaClient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bGestioEquips)
                        .addGap(18, 18, 18)
                        .addComponent(bEquipsReparacio))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bGestioEquipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGestioEquipsActionPerformed
        // TODO add your handling code here:
        FinestraGestio a = new FinestraGestio(this, rootPaneCheckingEnabled);
        a.setVisible(true);
    }//GEN-LAST:event_bGestioEquipsActionPerformed

    private void mEquipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEquipsActionPerformed
        // TODO add your handling code here:
        FinestraEquipsReparacio a = new FinestraEquipsReparacio(this, rootPaneCheckingEnabled);
        a.setVisible(true);
    }//GEN-LAST:event_mEquipsActionPerformed

    private void bAltaClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAltaClientActionPerformed
        // TODO add your handling code here:
        FinestraClient a = new FinestraClient(this, rootPaneCheckingEnabled);
        a.setVisible(true);
    }//GEN-LAST:event_bAltaClientActionPerformed

    private void bEquipsReparacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEquipsReparacioActionPerformed
        // TODO add your handling code here:
        FinestraEquipsReparacio a = new FinestraEquipsReparacio(this, rootPaneCheckingEnabled);
        a.setVisible(true);
    }//GEN-LAST:event_bEquipsReparacioActionPerformed

    private void mAltaClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAltaClActionPerformed
        // TODO add your handling code here:
        FinestraClient a = new FinestraClient(this, rootPaneCheckingEnabled);
        a.setVisible(true);
    }//GEN-LAST:event_mAltaClActionPerformed

    private void mGestioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGestioActionPerformed
        // TODO add your handling code here:
        FinestraGestio a = new FinestraGestio(this, rootPaneCheckingEnabled);
        a.setVisible(true);
    }//GEN-LAST:event_mGestioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinestraPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinestraPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinestraPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinestraPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinestraPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAltaClient;
    private javax.swing.JButton bEquipsReparacio;
    private javax.swing.JButton bGestioEquips;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblTitol;
    private javax.swing.JMenuItem mAltaCl;
    private javax.swing.JMenuItem mEquips;
    private javax.swing.JMenuItem mGestio;
    // End of variables declaration//GEN-END:variables
}
