/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import controlador.*;
import codi.*;
/**
 *
 * @author alumno
 */
public class Finestra extends javax.swing.JFrame {
    
    Dada d = new Dada();
    Controlador c = new Controlador();
    /**
     * Creates new form Finestra
     */
    public Finestra() {
        initComponents();
        setLocationRelativeTo(null);
        txtId.setEditable(false);
        txtNotes.setEditable(false);
        bAnterior.setEnabled(false);
        bSeguent.setEnabled(false);
    }
    
    private void actualitza(Dada d) {
        txtId.setText(String.valueOf(d.getId()));
        txtNotes.setText(d.getNota());
    }
    
    private Dada ompliDada() {
        String n = txtNotes.getText();
        Dada a = new Dada(n);
        return a;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBuscar = new javax.swing.JLabel();
        txtBuscarId = new javax.swing.JTextField();
        bCercar = new javax.swing.JButton();
        bTots = new javax.swing.JButton();
        bAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNotes = new javax.swing.JTextField();
        bEixir = new javax.swing.JButton();
        bAnterior = new javax.swing.JButton();
        bSeguent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBuscar.setText("ID a buscar: ");

        bCercar.setText("Cercar");
        bCercar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCercarActionPerformed(evt);
            }
        });

        bTots.setText("Tots");
        bTots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTotsActionPerformed(evt);
            }
        });

        bAgregar.setText("Agregar");
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        jLabel2.setText("Notas:");

        bEixir.setText("Eixir");
        bEixir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEixirActionPerformed(evt);
            }
        });

        bAnterior.setText("<");
        bAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnteriorActionPerformed(evt);
            }
        });

        bSeguent.setText(">");
        bSeguent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSeguentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bAnterior)
                        .addGap(18, 18, 18)
                        .addComponent(bSeguent)
                        .addGap(74, 74, 74)
                        .addComponent(bEixir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblBuscar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBuscarId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(bCercar)
                                .addGap(18, 18, 18)
                                .addComponent(bTots)
                                .addGap(185, 185, 185)
                                .addComponent(bAgregar))
                            .addComponent(txtNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAgregar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBuscar)
                            .addComponent(txtBuscarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bCercar)
                            .addComponent(bTots))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txtNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bEixir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bAnterior)
                        .addComponent(bSeguent)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bTotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTotsActionPerformed
        // TODO add your handling code here:
        bAnterior.setEnabled(true);
        bSeguent.setEnabled(true);
        
        actualitza(c.primera());
    }//GEN-LAST:event_bTotsActionPerformed

    private void bCercarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCercarActionPerformed
        // TODO add your handling code here:
        bAnterior.setEnabled(false);
        bSeguent.setEnabled(false);
        try {
            int i = Integer.parseInt(txtBuscarId.getText());
            Dada a = c.buscarPerId(i);
            txtId.setText(String.valueOf(a.getId()));
            txtNotes.setText(a.getNota());
        } catch (NumberFormatException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_bCercarActionPerformed

    private void bEixirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEixirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bEixirActionPerformed

    private void bAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnteriorActionPerformed
        // TODO add your handling code here:
        d = c.anterior();
        actualitza(d);
    }//GEN-LAST:event_bAnteriorActionPerformed

    private void bSeguentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSeguentActionPerformed
        // TODO add your handling code here:
        d = c.seguent();
        actualitza(d);
    }//GEN-LAST:event_bSeguentActionPerformed

    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
        // TODO add your handling code here:
        bAnterior.setEnabled(false);
        bSeguent.setEnabled(false);
        if(bAgregar.getText().equals("Agregar")) {
            txtNotes.setText("");
            txtId.setText("");
            
            txtNotes.setEditable(true);
            
            bAgregar.setText("OK");
            
        } else {
            txtNotes.setEditable(false);
            
            bAgregar.setText("Agregar");
            d = ompliDada();
            if(d != null) {
                c.nova(d);
            } else {
                d = c.anterior();
                actualitza(d);
            }
        }
    }//GEN-LAST:event_bAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Finestra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregar;
    private javax.swing.JButton bAnterior;
    private javax.swing.JButton bCercar;
    private javax.swing.JButton bEixir;
    private javax.swing.JButton bSeguent;
    private javax.swing.JButton bTots;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JTextField txtBuscarId;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNotes;
    // End of variables declaration//GEN-END:variables
}
