/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import java.io.File;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Serie;
import model.Acces;
import model.LlistaSeries;
/**
 *
 * @author alumno
 */
public class Finestra extends javax.swing.JFrame {

    /**
     * Creates new form Finestra
     */
    public Finestra() {
        initComponents();
        setLocationRelativeTo(null);
        actualitza(c.primera());
    }
    public Serie s = new Serie();
    public static Controlador c = new Controlador();
    
    public static Controlador getControlador() { return c; }
    public static void setControlador(Controlador a) { c = a; } 
    
    public void actualitza(Serie s) {
        txtTitol.setText(s.getTitol());
        txtGenere.setText(s.getGenere());
        txtProductors.setText(s.getProductors());
        txtAny.setText(String.valueOf(s.getAny()));
        txtTemporades.setText(String.valueOf(s.getTemporades()));
        txtValoracio.setText(String.valueOf(s.getValoracio()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        bPrimer = new javax.swing.JButton();
        bAnterior = new javax.swing.JButton();
        bUltim = new javax.swing.JButton();
        bSeguent = new javax.swing.JButton();
        bAfegir = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        bActualitzar = new javax.swing.JButton();
        lblTitol = new javax.swing.JLabel();
        lblGenere = new javax.swing.JLabel();
        lblProductors = new javax.swing.JLabel();
        lblAny = new javax.swing.JLabel();
        lblTemporades = new javax.swing.JLabel();
        lblValoracio = new javax.swing.JLabel();
        txtProductors = new javax.swing.JTextField();
        txtTitol = new javax.swing.JTextField();
        txtGenere = new javax.swing.JTextField();
        txtAny = new javax.swing.JTextField();
        txtTemporades = new javax.swing.JTextField();
        txtValoracio = new javax.swing.JTextField();
        bEixir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        bMenuEixir = new javax.swing.JMenu();
        bMenuObrir = new javax.swing.JMenuItem();
        bMenuGuardar = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Les meues Sèries");
        setResizable(false);

        bPrimer.setText("|<");
        bPrimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrimerActionPerformed(evt);
            }
        });

        bAnterior.setText("<");
        bAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnteriorActionPerformed(evt);
            }
        });

        bUltim.setText(">|");
        bUltim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUltimActionPerformed(evt);
            }
        });

        bSeguent.setText(">");
        bSeguent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSeguentActionPerformed(evt);
            }
        });

        bAfegir.setText("+");
        bAfegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAfegirActionPerformed(evt);
            }
        });

        bEliminar.setText("-");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        bActualitzar.setText("A");
        bActualitzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualitzarActionPerformed(evt);
            }
        });

        lblTitol.setText("Títol:");

        lblGenere.setText("Gènere:");

        lblProductors.setText("Productors:");

        lblAny.setText("Any:");

        lblTemporades.setText("Temporades:");

        lblValoracio.setText("Valoració Personal:");

        txtProductors.setEditable(false);

        txtTitol.setEditable(false);

        txtGenere.setEditable(false);

        txtAny.setEditable(false);

        txtTemporades.setEditable(false);

        txtValoracio.setEditable(false);

        bEixir.setText("Eixir");
        bEixir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEixirActionPerformed(evt);
            }
        });

        bMenuEixir.setText("Arxiu");
        bMenuEixir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMenuEixirActionPerformed(evt);
            }
        });

        bMenuObrir.setText("Obrir");
        bMenuObrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMenuObrirActionPerformed(evt);
            }
        });
        bMenuEixir.add(bMenuObrir);

        bMenuGuardar.setText("Guardar com...");
        bMenuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMenuGuardarActionPerformed(evt);
            }
        });
        bMenuEixir.add(bMenuGuardar);

        jMenuItem4.setText("Eixir");
        bMenuEixir.add(jMenuItem4);

        jMenuBar1.add(bMenuEixir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bEixir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bPrimer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(bAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(bSeguent)
                            .addGap(18, 18, 18)
                            .addComponent(bUltim)
                            .addGap(18, 18, 18)
                            .addComponent(bAfegir)
                            .addGap(18, 18, 18)
                            .addComponent(bEliminar)
                            .addGap(18, 18, 18)
                            .addComponent(bActualitzar))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblAny)
                                .addComponent(lblGenere)
                                .addComponent(lblProductors)
                                .addComponent(lblValoracio)
                                .addComponent(lblTitol)
                                .addComponent(lblTemporades))
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtValoracio, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                                .addComponent(txtGenere)
                                .addComponent(txtAny)
                                .addComponent(txtTemporades)
                                .addComponent(txtTitol)
                                .addComponent(txtProductors)))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bPrimer)
                    .addComponent(bAnterior)
                    .addComponent(bSeguent)
                    .addComponent(bUltim)
                    .addComponent(bAfegir)
                    .addComponent(bEliminar)
                    .addComponent(bActualitzar))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitol))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGenere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGenere))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProductors, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProductors))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAny))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTemporades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTemporades))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValoracio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValoracio))
                .addGap(38, 38, 38)
                .addComponent(bEixir)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bMenuObrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMenuObrirActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".dat", "dat");
        JFileChooser a = new JFileChooser();
        a.setFileSelectionMode(JFileChooser.FILES_ONLY);
        a.setFileFilter(filter);
        int resultat = a.showDialog(a, "Acceptar");
        File fitxer = a.getSelectedFile();
        if((fitxer == null) || fitxer.getName().contentEquals("")) {
        }
        c.setFitxer(fitxer);
        c.carregar();
        actualitza(c.primera());
    }//GEN-LAST:event_bMenuObrirActionPerformed

    private void bPrimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrimerActionPerformed
        // TODO add your handling code here:
        s = c.primera();
        actualitza(s);
    }//GEN-LAST:event_bPrimerActionPerformed

    private void bAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnteriorActionPerformed
        // TODO add your handling code here:
        s = c.anterior();
        actualitza(s);
    }//GEN-LAST:event_bAnteriorActionPerformed

    private void bSeguentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSeguentActionPerformed
        // TODO add your handling code here:
        s = c.seguent();
        actualitza(s);
    }//GEN-LAST:event_bSeguentActionPerformed

    private void bUltimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUltimActionPerformed
        // TODO add your handling code here:
        s = c.ultima();
        actualitza(s);
    }//GEN-LAST:event_bUltimActionPerformed

    private void bAfegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAfegirActionPerformed
        // TODO add your handling code here:
        Formulari a = new Formulari(this, rootPaneCheckingEnabled);
        a.setVisible(true);
        actualitza(s);
    }//GEN-LAST:event_bAfegirActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        // TODO add your handling code here:
        c.eliminar();
        s = c.anterior();
        actualitza(s);
    }//GEN-LAST:event_bEliminarActionPerformed

    private void bActualitzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualitzarActionPerformed
        // TODO add your handling code here:
        if(bActualitzar.getText().equals("A")) {
            txtTitol.setEditable(true);
            txtGenere.setEditable(true);
            txtProductors.setEditable(true);
            txtAny.setEditable(true);
            txtTemporades.setEditable(true);
            txtValoracio.setEditable(true);
            
            bActualitzar.setText("OK");
        } else {
            txtTitol.setEditable(false);
            txtGenere.setEditable(false);
            txtProductors.setEditable(false);
            txtAny.setEditable(false);
            txtTemporades.setEditable(false);
            txtValoracio.setEditable(false);
            
            bActualitzar.setText("A");
            
            s = ompliSerie();
            c.actualitzar(s);
            
        }
    }//GEN-LAST:event_bActualitzarActionPerformed

    private void bEixirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEixirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bEixirActionPerformed

    private void bMenuEixirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMenuEixirActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_bMenuEixirActionPerformed

    private void bMenuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMenuGuardarActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".dat", "dat");
        JFileChooser a = new JFileChooser();
        a.setFileSelectionMode(JFileChooser.FILES_ONLY);
        a.setFileFilter(filter);
        int resultat = a.showDialog(a, "Acceptar");
        File fitxer = a.getSelectedFile();
        if((fitxer == null) || fitxer.getName().contentEquals("")) {
        }
        c.guardarCom(fitxer);
    }//GEN-LAST:event_bMenuGuardarActionPerformed

    
    private Serie ompliSerie() {
        try {
            int any = Integer.parseInt(txtAny.getText());
            int temporades = Integer.parseInt(txtTemporades.getText());
            int valoracio = Integer.parseInt(txtValoracio.getText());
            if(valoracio > 10 || valoracio < 0) {
                JOptionPane.showMessageDialog(null, "La valoració és un enter de 0 a 10");
            }
            Serie s = new Serie(txtTitol.getText(), txtGenere.getText(), txtProductors.getText(), 
            any, temporades, valoracio);
            return s;
            
        } catch(NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Dades incorrectes");
            s = null;
            return s;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finestra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Finestra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualitzar;
    private javax.swing.JButton bAfegir;
    private javax.swing.JButton bAnterior;
    private javax.swing.JButton bEixir;
    private javax.swing.JButton bEliminar;
    private javax.swing.JMenu bMenuEixir;
    private javax.swing.JMenuItem bMenuGuardar;
    private javax.swing.JMenuItem bMenuObrir;
    private javax.swing.JButton bPrimer;
    private javax.swing.JButton bSeguent;
    private javax.swing.JButton bUltim;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JLabel lblAny;
    private javax.swing.JLabel lblGenere;
    private javax.swing.JLabel lblProductors;
    private javax.swing.JLabel lblTemporades;
    private javax.swing.JLabel lblTitol;
    private javax.swing.JLabel lblValoracio;
    private javax.swing.JTextField txtAny;
    private javax.swing.JTextField txtGenere;
    private javax.swing.JTextField txtProductors;
    private javax.swing.JTextField txtTemporades;
    private javax.swing.JTextField txtTitol;
    private javax.swing.JTextField txtValoracio;
    // End of variables declaration//GEN-END:variables
}
