/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import model.*;
import controlador.*;
import vista.Finestra;

/**
 *
 * @author alumno
 */
public class Formulari extends javax.swing.JDialog {

    /**
     * Creates new form Formulari
     */
    public Formulari(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }
    Serie s = new Serie();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitol = new javax.swing.JLabel();
        lblGenere = new javax.swing.JLabel();
        lblProductors = new javax.swing.JLabel();
        lblAny = new javax.swing.JLabel();
        lblTemporades = new javax.swing.JLabel();
        lblValoració = new javax.swing.JLabel();
        txtTitol = new javax.swing.JTextField();
        txtGenere = new javax.swing.JTextField();
        txtProductors = new javax.swing.JTextField();
        txtAny = new javax.swing.JTextField();
        txtTemporades = new javax.swing.JTextField();
        txtValoracio = new javax.swing.JTextField();
        bCancelar = new javax.swing.JButton();
        bAcceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Afegir Sèrie");
        setResizable(false);

        lblTitol.setText("Títol:");

        lblGenere.setText("Gènere:");

        lblProductors.setText("Productors:");

        lblAny.setText("Any:");

        lblTemporades.setText("Temporades:");

        lblValoració.setText("Valoració Personal(0-10):");

        bCancelar.setText("Cancel·lar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bAcceptar.setText("Acceptar");
        bAcceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAcceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(251, Short.MAX_VALUE)
                        .addComponent(bAcceptar)
                        .addGap(34, 34, 34)
                        .addComponent(bCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitol)
                            .addComponent(lblValoració)
                            .addComponent(lblGenere)
                            .addComponent(lblProductors)
                            .addComponent(lblAny)
                            .addComponent(lblTemporades))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTitol)
                            .addComponent(txtGenere, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(txtValoracio, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(txtTemporades)
                            .addComponent(txtAny)
                            .addComponent(txtProductors))))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitol)
                    .addComponent(txtTitol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenere)
                    .addComponent(txtGenere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProductors)
                    .addComponent(txtProductors, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAny)
                    .addComponent(txtAny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTemporades)
                    .addComponent(txtTemporades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValoració)
                    .addComponent(txtValoracio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar)
                    .addComponent(bAcceptar))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bAcceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAcceptarActionPerformed
        // TODO add your handling code here:
        ompliSerie();
        if(s != null) {
            Finestra.getControlador().nova(s);
        }
        this.setVisible(false);
    }//GEN-LAST:event_bAcceptarActionPerformed
    
     private Serie ompliSerie() {
        try {
            int any = Integer.parseInt(txtAny.getText());
            int temporades = Integer.parseInt(txtTemporades.getText());
            int valoracio = Integer.parseInt(txtValoracio.getText());
            if(valoracio > 10 || valoracio < 0) {
                JOptionPane.showMessageDialog(null, "La valoració és un enter de 0 a 10");
            }  
            s = new Serie(txtTitol.getText(), txtGenere.getText(), txtProductors.getText(), 
            any, temporades, valoracio);
            return s;
            
        } catch(NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Dades incorrectes");
            s = null;
            return s;
        }
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Formulari dialog = new Formulari(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAcceptar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JLabel lblAny;
    private javax.swing.JLabel lblGenere;
    private javax.swing.JLabel lblProductors;
    private javax.swing.JLabel lblTemporades;
    private javax.swing.JLabel lblTitol;
    private javax.swing.JLabel lblValoració;
    private javax.swing.JTextField txtAny;
    private javax.swing.JTextField txtGenere;
    private javax.swing.JTextField txtProductors;
    private javax.swing.JTextField txtTemporades;
    private javax.swing.JTextField txtTitol;
    private javax.swing.JTextField txtValoracio;
    // End of variables declaration//GEN-END:variables
}
